/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_leixiaohua1020_sffmpegandroidtranscoder_I2C */

#ifndef _Included_com_leixiaohua1020_sffmpegandroidtranscoder_I2C
#define _Included_com_leixiaohua1020_sffmpegandroidtranscoder_I2C
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_leixiaohua1020_sffmpegandroidtranscoder_I2C
 * Method:    write
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_leixiaohua1020_sffmpegandroidtranscoder_I2C_write
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_leixiaohua1020_sffmpegandroidtranscoder_I2C
 * Method:    read
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_leixiaohua1020_sffmpegandroidtranscoder_I2C_read
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
