/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_leixiaohua1020_sffmpegandroidtranscoder_I2CFPGA */

#ifndef _Included_com_leixiaohua1020_sffmpegandroidtranscoder_I2CFPGA
#define _Included_com_leixiaohua1020_sffmpegandroidtranscoder_I2CFPGA
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_leixiaohua1020_sffmpegandroidtranscoder_I2CFPGA
 * Method:    Open
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_leixiaohua1020_sffmpegandroidtranscoder_I2CFPGA_Open
  (JNIEnv *, jobject);

/*
 * Class:     com_leixiaohua1020_sffmpegandroidtranscoder_I2CFPGA
 * Method:    Close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_leixiaohua1020_sffmpegandroidtranscoder_I2CFPGA_Close
  (JNIEnv *, jobject);

/*
 * Class:     com_leixiaohua1020_sffmpegandroidtranscoder_I2CFPGA
 * Method:    Ioctl
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_leixiaohua1020_sffmpegandroidtranscoder_I2CFPGA_Ioctl
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
