/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_leixiaohua1020_sffmpegandroidtranscoder_serial */

#ifndef _Included_com_leixiaohua1020_sffmpegandroidtranscoder_serial
#define _Included_com_leixiaohua1020_sffmpegandroidtranscoder_serial
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_leixiaohua1020_sffmpegandroidtranscoder_serial
 * Method:    Open
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_leixiaohua1020_sffmpegandroidtranscoder_serial_Open
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_leixiaohua1020_sffmpegandroidtranscoder_serial
 * Method:    Close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_leixiaohua1020_sffmpegandroidtranscoder_serial_Close
  (JNIEnv *, jobject);

/*
 * Class:     com_leixiaohua1020_sffmpegandroidtranscoder_serial
 * Method:    Read
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_com_leixiaohua1020_sffmpegandroidtranscoder_serial_Read
  (JNIEnv *, jobject);

/*
 * Class:     com_leixiaohua1020_sffmpegandroidtranscoder_serial
 * Method:    Write
 * Signature: ([II)I
 */
JNIEXPORT jintArray JNICALL Java_com_leixiaohua1020_sffmpegandroidtranscoder_serial_Write
  (JNIEnv *, jobject, jintArray, jint);

#ifdef __cplusplus
}
#endif
#endif
